create sequence hibernate_sequence start with 1 increment by 1;
create table users
(
    id         bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp not null,
    name       varchar(255),
    balance    bigint,
    version    int,
    primary key (id)
);

create table transactions
(
    transaction_id bigint    not null,
    created_at     timestamp not null,
    updated_at     timestamp not null,
    amount         bigint    not null,
    user_id        bigint    not null,
    type           int,
    version        int,
    primary key (transaction_id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

insert into users
values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'John', 100, 0);
insert into users
values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Jack', 100, 0);
insert into users
values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'David', 100, 0);

insert into transactions
values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 100, 1, 1, 0);
insert into transactions
values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 100, 2, 1, 0);
insert into transactions
values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 100, 3, 1, 0);
commit;